version: "3.7"
services:
  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - ceres-net
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME:-ceresdb}
      MYSQL_USER: ${DATABASE_USER:-ceres}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-strongPassword}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD:-rootPassword}
networks:
  ceres-net:
