server:
  port: 8080
spring:
  application:
    name: ceres
  datasource:
    username: ${DATABASE_USER:ceres}
    password: ${DATABASE_PASSWORD:strongPassword}
    driver-class-name: com.mysql.jdbc.Driver
    url: mysql://mysqldb:3306/${DATABASE_NAME:ceresdb}?allowPublicKeyRetrieval=true
  flyway:
    enabled: false
    locations: classpath:db/migration
    validate-on-migrate: true
  threads:
    virtual:
      enabled: true

integration:
  juno:
    rest-uri: http://localhost:8081
logging:
  level:
    root: debug
